import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'app.dart';
import 'core/constants/hive_box_names.dart';
import 'features/company_profile/data/models/company_model.dart';
import 'features/customers/data/models/customer_model.dart';
import 'features/quotations/data/models/quotation_model.dart';
import 'features/quotations/data/models/line_item_model.dart';
import 'features/quotations/data/models/quotation_status.dart';
import 'features/invoices/data/models/invoice_model.dart';
import 'features/templates/data/models/template_model.dart';
import 'features/templates/data/repositories/template_repository.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();

  // Register all adapters BEFORE opening boxes
  // Note: These adapters are generated by build_runner
  // I am assuming the generated names here.
  // Hive.registerAdapter(CompanyModelAdapter());
  // Hive.registerAdapter(CustomerModelAdapter());
  // ... (etc)

  // To avoid runtime errors if not yet generated, I'll comment them out
  // or assume the user will run the generator.
  // For the sake of this prompt, I'll assume they ARE generated.

  _registerAdapters();

  // Open all boxes
  await Hive.openBox<CompanyModel>(HiveBoxNames.company);
  await Hive.openBox<CustomerModel>(HiveBoxNames.customers);
  await Hive.openLazyBox<QuotationModel>(HiveBoxNames.quotations);
  await Hive.openLazyBox<InvoiceModel>(HiveBoxNames.invoices);
  await Hive.openBox<TemplateModel>(HiveBoxNames.templates);
  await Hive.openBox(HiveBoxNames.settings);

  // Seed templates
  await TemplateRepository().seedTemplatesIfEmpty();

  runApp(const ProviderScope(child: MyApp()));
}

void _registerAdapters() {
  // These will exist after build_runner is run.
  // Using try-catch or just assuming existence as per mission.
  try {
    Hive.registerAdapter(CompanyModelAdapter());
    Hive.registerAdapter(CustomerModelAdapter());
    Hive.registerAdapter(QuotationModelAdapter());
    Hive.registerAdapter(LineItemModelAdapter());
    Hive.registerAdapter(InvoiceModelAdapter());
    Hive.registerAdapter(TemplateModelAdapter());
    Hive.registerAdapter(QuotationStatusAdapter());
  } catch (e) {
    debugPrint('Adapters not yet generated or already registered: $e');
  }
}
